 @if(isset($quotations))
 <style type="text/css">
    .invoiceBody{
        margin-top:10px;
        background:#eee;
        padding: 10px;

    }
    .ratings {
        margin-right: 10px
    }

    .ratings i {
        color: #cecece;
        font-size: 14px
    }

    .rating-color {
        color: #fbc634 !important
    }

    .review-count {
        font-weight: 400;
        margin-bottom: 2px;
        font-size: 14px !important
    }

    .small-ratings i {
        color: #cecece
    }

    .review-stat {
        font-weight: 300;
        font-size: 18px;
        margin-bottom: 2px
    }
</style>

<div class="col-md-12>">
    <div class="panel panel-info">

        <div class="col-lg-12 invoiceBody">
            <div class="invoice-details mt25 row">
               
            <div class="well col-6">
                <ul class="list-unstyled mb0">
                    <li>
                        <?php 
                        $TS = number_format($quotations->relSuppliers->SupplierRatings->sum('total_score'),2);
                        $TC = $quotations->relSuppliers->SupplierRatings->count();

                        $totalScore = isset($TS)?$TS:0;
                        $totalCount = isset($TC)?$TC:0;
                    ?>

                        <div class="ratings">
                            <a href="{{route('pms.supplier.profile',$quotations->relSuppliers->id)}}" target="_blank"><span>Rating:</span></a> {!!ratingGenerate($totalScore,$totalCount)!!}
                        </div>
                        <h5 class="review-count"></h5>
                    </li>
                    <li><strong>{{__('Supplier')}} :</strong> {{$quotations->relSuppliers->name}}</li>
                    <li><strong>{{__('Email')}} :</strong> {{$quotations->relSuppliers->email}}</li>
                    <li><strong>{{__('Phone')}} :</strong> {{$quotations->relSuppliers->phone}}</li>
                    
                </ul>
            </div>
             <div class="col-6">
                <ul class="list-unstyled mb0 pull-right">
                    <li><strong>{{__('Date')}} :</strong> {{date('d-m-Y',strtotime($quotations->quotation_date))}}</li>
                    <li><strong>{{__('Reference No')}}:</strong> {{$quotations->reference_no}}</li>
                    <li><strong>{{__('RFP No')}}:</strong> {{$quotations->relRequestProposal->reference_no}}</li>
                    <li><strong>{{__('Generated By')}}:</strong> {{$quotations->relRequestProposal->createdBy->name}}</li>

                    
            </ul>
            </div>
        
    </div>
</div>
<div class="table-responsive">

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Sl No.</th>
                <th>Category</th>
                <th>Product</th>
                <th>Unit Price</th>
                <th>Qty</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>


            @foreach($quotations->relQuotationItems as $key=>$item)
            <tr>
                <td>{{$key+1}}</td>
                <td>{{$item->relProduct->category->name}}</td>
                <td>{{$item->relProduct->name}}</td>
                <td>{{$item->unit_price}}</td>
                <td>{{$item->qty}}</td>
                <td>{{$item->total_price}}</td>
            </tr>
            @endforeach
            
            <tr>
                <td colspan="3" class="text-right">Total</td>
                <td colspan="">{{$quotations->relQuotationItems->sum('unit_price')}}</td>
                <td colspan="">{{$quotations->relQuotationItems->sum('qty')}}</td>
                <td colspan="">{{$quotations->relQuotationItems->sum('total_price')}}</td>
            </tr>

            <tr>
                <td colspan="5" class="text-right">Discount (%)</td>
                <td>-<?= $discount = ($quotations->discount * $quotations->relQuotationItems->sum('total_price'))/100; ?> ({{$quotations->discount}})</td>
            </tr>
            <tr>
                <td colspan="5" class="text-right">Vat (%)</td>
                <td>+<?= $vat = ($quotations->vat * $quotations->relQuotationItems->sum('total_price'))/100; ?> ({{$quotations->vat}})</td>
            </tr>
            <tr>
                <td colspan="5" class="text-right">Total Amount</td>
                <td>{{$quotations->gross_price}}</td>
            </tr>
            @if(!empty($quotations->remarks))
            <tr>
                <td class="text-left">Remarks</td>
                <td  colspan="5">{{$quotations->remarks}}</td>
            </tr>
            @endif

            @if(!empty($quotations->note))
            <tr>
                <td class="text-left">Note</td>
                <td class="text-left" colspan="5">{{$quotations->note}}</td>
            </tr>
            @endif

        </tbody>
    </table>
</div>
</div>
</div>
@endif